from __future__ import annotations

import argparse
import hashlib
import json
import random
from datetime import datetime, timedelta, timezone
from typing import Any

SCENARIOS: dict[str, dict[str, Any]] = {
    "flood": {
        "kind": "flood",
        "center": (-3.7038, 40.4168),
        "area": "Synthetic River District",
        "titles": ["River flooding reported", "Flooding affecting low-lying roads", "Water levels rising near river"],
        "severity": 0.78,
    },
    "wildfire": {
        "kind": "wildfire",
        "center": (-0.3763, 39.4699),
        "area": "Synthetic Pine Ridge",
        "titles": ["Wildfire reported near ridge", "Forest fire producing smoke", "Vegetation fire expanding"],
        "severity": 0.86,
    },
    "earthquake": {
        "kind": "earthquake",
        "center": (-4.4214, 36.7213),
        "area": "Synthetic Coastal Zone",
        "titles": ["Earthquake detected", "Seismic event reported", "Ground shaking reported"],
        "severity": 0.64,
    },
}

SOURCES = [
    ("Synthetic Emergency Agency", "cap", True, 0.90),
    ("Synthetic Local News", "rss", False, 0.58),
    ("Synthetic Volunteer Network", "field", False, 0.48),
    ("Synthetic Sensor Feed", "json", False, 0.70),
]
MAX_COUNT = 100_000


def _id(seed: int, scenario: str, idx: int, source: str) -> str:
    return hashlib.sha256(f"{seed}:{scenario}:{idx}:{source}".encode()).hexdigest()[:24]


def make_event(rng: random.Random, seed: int, scenario: str, idx: int, base_time: datetime) -> dict[str, Any]:
    spec = SCENARIOS[scenario]
    source_name, source_type, official, confidence = rng.choice(SOURCES)
    lon0, lat0 = spec["center"]

    # Most reports describe the same evolving incident. A minority are deliberate outliers.
    outlier = rng.random() < 0.12
    spread = 1.2 if outlier else 0.11
    lon = lon0 + rng.uniform(-spread, spread)
    lat = lat0 + rng.uniform(-spread, spread)
    observed = base_time + timedelta(minutes=rng.randint(-35, 95 if not outlier else 900))
    severity = max(0.0, min(1.0, spec["severity"] + rng.uniform(-0.13, 0.13)))

    geometry: dict[str, Any] | None = {"type": "Point", "coordinates": [round(lon, 6), round(lat, 6)]}
    if rng.random() < 0.15:
        geometry = None

    title = rng.choice(spec["titles"])
    if outlier:
        title = f"Unrelated {scenario} report for dedupe testing"

    return {
        "id": _id(seed, scenario, idx, source_name),
        "synthetic": True,
        "environment": "simulation",
        "kind": spec["kind"],
        "title": title,
        "description": f"Synthetic test report #{idx}. This record is generated by crisisweave-sim and is not a real emergency.",
        "observed_at": observed.isoformat(),
        "expires_at": None,
        "severity": round(severity, 3),
        "confidence": round(max(0.1, min(0.98, confidence + rng.uniform(-0.08, 0.08))), 3),
        "official": official,
        "geometry": geometry,
        "area": spec["area"] if rng.random() > 0.1 else None,
        "source": {
            "name": source_name,
            "type": source_type,
            "url": None,
            "source_id": f"SIM-{scenario.upper()}-{idx:05d}",
        },
        "evidence": [{"source": source_name, "weight": confidence, "note": "synthetic test evidence"}],
        "raw": {"synthetic": True, "seed": seed, "outlier": outlier},
        "tags": ["synthetic", "test", scenario],
    }


def generate(scenario: str, count: int, seed: int) -> list[dict[str, Any]]:
    if scenario != "mixed" and scenario not in SCENARIOS:
        raise ValueError("unknown scenario")
    if count < 1 or count > MAX_COUNT:
        raise ValueError(f"count must be between 1 and {MAX_COUNT}")
    rng = random.Random(seed)
    base_time = datetime(2026, 1, 1, 12, 0, tzinfo=timezone.utc)
    names = list(SCENARIOS) if scenario == "mixed" else [scenario]
    return [make_event(rng, seed, names[i % len(names)], i, base_time) for i in range(count)]


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate deterministic synthetic CrisisWeave events")
    parser.add_argument("--scenario", choices=[*SCENARIOS.keys(), "mixed"], default="mixed")
    parser.add_argument("--count", type=int, default=20)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()
    try:
        events = generate(args.scenario, args.count, args.seed)
    except ValueError as exc:
        raise SystemExit(str(exc)) from exc
    for event in events:
        print(json.dumps(event, ensure_ascii=False, allow_nan=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
